### PR TITLE
Expanded on the first counter tutorial

### PR DESCRIPTION
**Pull request by lvrbrtsn**
I got a little confused with the first counter tutorial and had to open the files to see how the original worked.

### CODE REVIEW

**Comment by sircharleswatson** [comment]
I agree that it'd be nice to show the `import`s and `init`s and things in the tutorials so that a person coming to them for the first time will see the whole code and be able to run it easier without having to leave the tutorial to go to the source and fill in the missing pieces (which aren't always easy to spot).

**Comment by evancz** [comment]
I think having code appear before imports will be even more confusing to people, so I'm not on board with this particular change. Generally speaking, I feel that tutorials that include *all* the code end up being much more distracting because you can't tell what the person is referring to anymore because there is all this extra stuff.

**Comment by evancz** [comment]
So I totally get the concern, but I don't think that this resolves it in a better way.

**Comment by lvrbrtsn** [comment]
@evancz Would you be open to me working on it more and trying again? Or is there somewhere else I could focus my efforts? I plan on making some Youtube videos going through these tutorials is that cool with you?

**Comment by evancz** [comment]
Generally I am pretty hesitant to change prose and flow of highly read articles like this in a piecemeal way because I tried to be considerate of the overall flow in the initial writing. If we make 10 prose changes over the course of a few months, it warrants a more complete review. So there may be problems in the existing version, but perhaps not to the extent that it'd need an urgent rewrite. So in terms of time management, this is just a hard thing to do because it will eventually *require* a bunch of time in a way that is not currently the case.

That said, making youtube videos would be great! One fact about the internet is that videos are less "viewed" than text, especially if it is more than 2 or 5 minutes. It's just about the risk that a 45 minute video is 80% things you know already, which is much harder to assess than with a blog post. So one way to augment and improve this resource would be to create separate supplementary materials and share them on elm-discuss, /r/elm, twitter, etc. I'd love to see more folks blogging this way!

From there we can bring back learnings, link to things directly if they are relevant, etc. Essentially, it can be totally independent of me or the things I maintain, which is a much less risky process. Also, when things go well, I have a data set to say, "ah, I have seen X's writing before, this should be fine"  in a way that is nearly impossible on a one-off prose change.

**Comment by lvrbrtsn** [comment]
Sounds good Evan! I will probably make some videos paired with blog posts and get cracking : ) Thank you!

**Comment by evancz** [comment]
Cool, looking forward to seeing them :)

**Pull request closed without merging**
