### PR TITLE
Mention the wiring of tasks for example 5

### PR DESCRIPTION
**Pull request by eskimoblood**

### CODE REVIEW

**Comment by epeli** [comment]
I'd like see bit more detailed explanation here (or link to one). As I'm just now learning Elm by reading this tutorial this part is left completely magic to me. "It just have be here to make things work". :/

**Comment by halfzebra** [comment]
You might find more details on the mater of using Ports for Tasks here [Reactivity — Basic Example](http://elm-lang.org/guide/reactivity#basic-example)

**Comment by siddharthist** [comment]
Maybe this could be merged, and then a more detailed explanation later? I think this is a lot better than nothing.

**Comment by evancz** [comment]
You don't have to do this stuff in 0.17 anymore. Best way to make something less confusing is to not have it anymore.

**Pull request closed without merging**
